matter-labs/era-compiler-llvm-context

src/eravm/context/function/llvm_runtime.rs, src/eravm/context/function/mod.rs
Adds `optnone` and `noinline` attributes to all functions if middle-end optimizations are disabled.
It should disable some RAM-demanding LLVM passes which cause OOM on large unoptimized codebases.
=> Add noinline+optnone attributes in M0

src/evm_version.rs, src/lib.rs
Adds an EVM version enum for usage throughout all compiler projects.
It is better to have one enum for all.
=> Add the EVM version enum

src/eravm/context/mod.rs, src/optimizer/settings/mod.rs, src/target_machine/mod.rs
Adds an optimizer flag to disable SC calls memoization.
Some applications require such optimizations to be disabled, e.g. for a bootloader upgrade.
=> Add a flag to disable SC calls memoization

src/eravm/context/function/runtime/deployer_call.rs, src/eravm/context/function/runtime/mod.rs, src/eravm/evm/create.rs
Now it is possible to use `deployer_call` using both heap and auxiliary heap from the same contract.
Vyper contracts can be using `create_minimal_proxy_to` with the auxiliary heap, and `create_from_blueprint` with the ordinary heap.
=> Add the deploy_call for both heaps

src/eravm/context/mod.rs, src/eravm/context/vyper_data.rs
Renames the Vyper forwarder to minimal proxy.
The name was changed by Vyper in v0.3.4.
=> Rename forwarder to minimal proxy

src/eravm/context/function/intrinsics.rs, src/eravm/evm/call.rs
Uses memmove for same address spaces.
memcpy doesn't work with overlapping memory regions.
=> Replace heap memcpy with memmove

src/eravm/context/function/llvm_runtime.rs, src/eravm/evm/call.rs, src/eravm/extensions/abi.rs
Add simulations for forwarding pointers through returns.
This will make some cases of contract interaction more efficient.
=> Add simulations for forwarding returns

src/eravm/const.rs, src/eravm/context/function/runtime/entry.rs, src/eravm/context/mod.rs, src/eravm/evm/call.rs, src/eravm/extensions/abi.rs
Adds a simulation to swap active pointers.
We are allowing 16 saved pointers now, where 0th will be the active one.
=> Support swapping 16 active pointers

src/optimizer/settings/mod.rs, src/target_machine/mod.rs
Adds the jump table density threshold optimizer parameter.
This parameter is required for the jump table optimization, which is useful for the EVM interpreter on EraVM.
=> Add the jump table density threshold optimizer parameter

src/debug_config/mod.rs
Support creating subfolders in `debug/`.
Compiler tester overrides IR dumps if they were produced by launching a test repeatedly with different modes.
This change should not break behavior expected from `era-compiler-llvm-context`.
Corresponding PR in compiler tester: https://github.com/matter-labs/era-compiler-tester/pull/11
=> feature: support subdirectories for debug dumps

src/eravm/context/mod.rs
Sets the `noinline` attribute for all calls in `-O0`.
It will prevent inlining of some runtime functions with `alwaysinline` attribute.
=> feat: set noinline attribute for all calls in -O0

src/eravm/const.rs, src/target_machine.rs
Fixes some API types by making them 64 bits.
Most of them turned out to be incorrect.
=> fix: linker API integer types

.github/workflows/dependencies_check.yaml
Add cross-dependency testing workflow.
With each PR, we'll be also checking the following repositories:
are building and tests are passing _with custom `era-compiler-llvm-context` version_ from the testing PR.
Additionally, if the branch with the same name exist in any of the dependencies (e.g. `era-compiler-common`, or `llvm-sys`, or `inkwell`) it will be taken instead of the default dependency.
To allow cross-testing common dependencies without requirements to create multiple PRs in various repositories.
=> ci: add cross-dependency testing workflow

Cargo.toml
Adds the revision part for semver of all dependencies.
Also, zkevm_opcode_defs has been moved to zksync-protocol monorepo.
`cargo update` will become more resilient.
=> fix: set full semver for dependencies

src/eravm/context/function/intrinsics.rs, src/evm/context/function/intrinsics.rs, src/evm/instructions/event.rs
1. Memcpy declaration pointer order.
2. Event intrinsics argument order.
=> fix: memcpy and event intrinsic argument order

Cargo.toml
Removes the `git` reference from `zkevm_opcode_defs` dependency.
=> fix: the zkevm_opcode_defs dependency

src/eravm/context/function/intrinsics.rs, src/eravm/evm/call.rs, src/evm/context/function/intrinsics.rs
Adds the `memmove` intrinsic for heap.
`MCOPY` instruction was unimplemented.
=> feat(evm): add memmove for heap

src/dependency.rs, src/eravm/context/mod.rs, src/eravm/evm/call.rs, src/eravm/mod.rs, src/evm/context/mod.rs, src/evm/instructions/call.rs
Fixes the library linking indeterminism.
The bytecode is not equal depending on when libraries are linked: at compile time or deploy (post-compile) time.
=> fix: library linking time indeterminism

deny.toml, src/eravm/context/function/runtime/entry.rs, src/eravm/context/mod.rs, src/eravm/evm/create.rs
Cleares return data after calling `CREATE`/`CREATE2` (`ContractDeployer` system contract for EraVM).
It is cleared on EVM, but not on EraVM.
=> fix(eravm): resets return data after calling CREATE

.github/workflows/ci.yaml, Cargo.toml, LLVM.lock, src/context/mod.rs, src/dependency.rs, src/eravm/const.rs, src/eravm/context/build.rs, src/eravm/context/function/intrinsics.rs, src/eravm/context/function/runtime/deployer_call.rs, src/eravm/context/mod.rs, src/eravm/context/tests.rs, src/eravm/context/yul_data.rs, src/eravm/evm/create.rs, src/eravm/extensions/const_array.rs, src/eravm/mod.rs, src/evm/context/mod.rs, src/lib.rs
Adds the support for linking factory dependencies for EraVM.
Contracts with unlinked libraries are not ready for deployment, and they cannot have the bytecode hash either.
It means that we need to link EraVM in two iterations: libraries first, factory dependencies later.
=> feat(eravm): linkage of factory dependencies

src/eravm/evm/call.rs
Removes the branch replacing call(0x04) with memcopy.
=> fix: remove the branch replacing call(0x04) with memcopy

src/eravm/context/evmla_data.rs, src/eravm/evm/create.rs, src/eravm/extensions/general.rs, src/evm/context/evmla_data.rs
Simplifies some EVMLA object namings.
Needed to get rid of additional codegen checks in zksolc.
=> fix: simplify EVMLA object naming

src/evm/context/function/intrinsics.rs
Adds the `pushdeployaddress` intrinsic.
LLVM PR: https://github.com/matter-labs/era-compiler-llvm/pull/795
=> feat: add the pushdeployaddress intrinsic

rust-toolchain.toml, src/evm/const.rs, src/evm/context/function/mod.rs, src/evm/context/mod.rs
1. Enables falling back to -Oz if the EVM runtime bytecode size is exceeded.
2. Enables the check for EVM runtime bytecode size of 24576 bytes.
3. Updates Rust to v1.85.1.
=> feat: enable fallback-Oz and check runtime code size

Cargo.toml, src/evm/const.rs, src/evm/context/mod.rs, src/evm/mod.rs, src/evm/warning.rs, src/lib.rs
Adds an enum to mimic *solc* error codes.
For now, only for runtime code size.
=> feat: mimic solc error codes

src/const.rs, src/eravm/const.rs, src/eravm/evm/create.rs, src/evm/const.rs, src/evm/context/function/mod.rs, src/evm/context/function/runtime/entry.rs, src/evm/context/mod.rs, src/evm/warning.rs
Refactors a couple of outdated constants.
=> chore: refactor outdated constants

src/evm/mod.rs
Fixes the minimal EVM deploy code constants used for compiling LLVM IR.
=> fix: EVM minimal deploy code used for LLVM IR

src/evm/context/function/runtime/entry.rs
Emits `evm.stop` instead of `unreachable` in `entry` function.
It will gracefully return from an EVM contract if there is no more caller to jump back to.
=> fix(evm): do not emit unreachable in entry function

Cargo.lock, src/evm/context/mod.rs, src/target_machine.rs
Sets the EVM assembly verbosity to always true.
It will include some useful markings, such as loop boundaries.
=> feat: set asm verbosity to true

.cargo/config.toml
=> fix: change the musl linker to rust-lld

.cargo/config.toml
Do not use rust-lld for Linux musl builds, it is unable to properly link the final executable in unified CI config.
To use the common code, we use `lld` on Linux in CI for all compilers.
Related https://github.com/matter-labs/era-compiler-ci/pull/81 to be merged before this one.
Tested here: https://github.com/matter-labs/era-compiler-solidity/actions/runs/15215151919
=> chore: do not use rust-lld for musl builds

src/evm/build.rs, src/evm/context/mod.rs
Removes some redundant unused fields.
=> fix: clean up interface for deploy-time linking

Cargo.toml, rust-toolchain.toml, src/context/traits/solidity_data.rs, src/debug_config/mod.rs, src/eravm/context/mod.rs, src/eravm/context/solidity_data.rs, src/eravm/evm/immutable.rs, src/eravm/extensions/const_array.rs, src/evm/const.rs, src/evm/context/mod.rs, src/evm/context/solidity_data.rs, src/evm/instructions/event.rs, src/evm/instructions/immutable.rs, src/optimizer/settings/mod.rs, src/target_machine.rs
Adds API for getting the spill area size.
=> feat: add API for getting the spill area size

src/evm/attribute.rs, src/evm/context/function/runtime/entry.rs, src/evm/mod.rs, src/lib.rs
Adds an LLVM string attribute `evm-entry-function` for EVM entry functions.
It is needed for LLVM to always put the entry function at the beginning of the bytecode without fragile explicit checks for function names.
=> feat(evm): add an LLVM attribute for EVM entry functions

Cargo.toml
Bumps sha2 to v0.10.9.
Can't update `revm` in compiler-tester otherwise.
=> chore: bump zkevm_opcode_defs and sha2
