Cargo.toml, src/optimizer/settings/mod.rs
Updates minor versions of all deps in Cargo.toml
They have not been updated for a long time.
=> Update dependencies in Cargo.toml

src/eravm/context/address_space.rs, src/eravm/evm/storage.rs
Adds the support for solc v0.8.24.
It was released by the Solidity developers recently.
=> Support solc v0.8.24

src/debug_config/mod.rs
=> fix: support subdirectories for debug dumps (#24)

CONTRIBUTING.md, Cargo.toml, README.md, src/eravm/evm/return.rs, src/eravm/extensions/call.rs
Applies the ZKsync rebranding.
=> fix: ZKsync rebranding

.github/pull_request_template.md, README.md, rust-toolchain.toml, src/eravm/context/function/llvm_runtime.rs, src/eravm/evm/call.rs, src/eravm/evm/ext_code.rs
Adds the EXTCODECOPY support.
Such precompile was added to System Contracts.
=> feat: support EXTCODECOPY

.github/workflows/license-secrets-check.yaml
Add advanced cargo checks: fmt, clippy, udeps (unused dependencies), audit
=> ci: add advanced cargo checks including fmt, clippy, and audit

.github/pull_request_template.md, Cargo.toml, rust-toolchain.toml, src/debug_config/mod.rs, src/eravm/context/build.rs, src/eravm/context/function/llvm_runtime.rs, src/eravm/context/function/mod.rs, src/eravm/context/function/runtime/default_call.rs, src/eravm/context/function/runtime/deployer_call.rs, src/eravm/context/mod.rs, src/eravm/mod.rs, src/evm/context/mod.rs, src/lib.rs, src/target_machine/mod.rs
Migrates to the new LLVM-based assembler and linker.
We want to have the full LLVM-based pipeline.
=> feat: migrate to the new assembler and linker

src/eravm/const.rs, src/eravm/mod.rs, src/lib.rs, src/target_machine.rs
Adds the disassembler endpoint.
=> feat: add the disassembler utils

src/eravm/context/build.rs, src/eravm/context/mod.rs, src/eravm/mod.rs, src/evm/context/build.rs, src/evm/context/mod.rs
Adds the support for IPFS hash.
Requested by a partner: https://github.com/zkSync-Community-Hub/zksync-developers/discussions/194
=> feat: support the IPFS hash

Cargo.toml, src/context/mod.rs, src/dependency.rs, src/eravm/context/build.rs, src/eravm/context/function/intrinsics.rs, src/eravm/context/mod.rs, src/eravm/mod.rs, src/evm/context/mod.rs, src/lib.rs
Supports the post-compile-time linkage.
Required for EVM equivalence: https://github.com/matter-labs/era-compiler-solidity/issues/102
=> feat: support post-compile-time library linking

.github/workflows/ci.yaml, .github/workflows/secrets-scanner.yaml
Add mandatory pr-checks.
To allow auto merge in PRs.
=> ci: add mandatory pr-checks

src/eravm/evm/create.rs
It has been moved to [zkvyper](https://github.com/matter-labs/era-compiler-vyper/pull/130).
=> fix: remove an obsolete Vyper proxy usage detector

src/eravm/evm/call.rs
Adds the missing system call type checks, so the compiler will not crash on `value.expect("Always exists")`.
=> fix: missing system call type checks

.github/workflows/dependencies.yaml
Fix dependency workflow.
Rework using `workflow_call` instead of `workflow_dispatch` to not require any private token, make things more secure.
=> ci: fix dependency workflow

src/const.rs, src/context/mod.rs, src/context/traits/mod.rs, src/context/traits/solidity_data.rs, src/eravm/context/solidity_data.rs, src/evm/context/function/intrinsics.rs, src/evm/context/mod.rs, src/evm/context/solidity_data.rs, src/evm/instructions/immutable.rs, src/lib.rs
Adds the support for EVM immutables.
=> feat(evm): support immutables

src/evm/instructions/storage.rs
Supports the transient storage in the EVM target.
=> feat(evm): transient storage

Cargo.toml, src/evm/mod.rs, src/lib.rs, src/optimizer/mod.rs, src/optimizer/settings/mod.rs
Adds a function to get minimal EVM deploy code.
=> feat: add minimal EVM deploy code

Cargo.lock, src/evm/mod.rs, src/lib.rs
Adds an endpoint for appending metadata to EVM bytecode.
=> feat(evm): add the metadata endpoint

.cargo/config.toml, .github/workflows/ci.yaml, .github/workflows/dependencies.yaml, .gitmodules, Cargo.lock, Cargo.toml, rust-toolchain.toml, src/context/attribute/mod.rs
=> feat: update to LLVM 19

src/debug_config/mod.rs, src/eravm/context/mod.rs, src/eravm/mod.rs, src/evm/context/mod.rs
=> fix: size fallback debug output
